# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96de928a74b1b60100e2f0fbd36b598a8bd0b33acdf3f45498cccc6493a7e597601776adf9697b568dc4754412b39f20570f9596887c8a4d2fc931959242d71

test:
  secret_key_base: 65ab17b3471a36aa3940445afb94fc77563d6d6f3fa8215ec66cea39968f85179660a2ceac1ae26062e11d43c782dff9ec6da34bd90c4586322379e1a65da5f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
